{
 "title": "Retail - CockroachDB: Central",
 "tags": [
  "CockroachDB",
  "VMWare"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health, Clock & Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes: $cluster",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Uptime: $cluster",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean RPC Clock Offset: $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"cockroachdb\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clock Offset: $cluster",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"cockroachdb\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Query Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$cluster Transaction Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_99{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_99{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_95{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_95{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 90th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_90{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 90th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_90{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 50th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_50{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 50th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_50{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Contention & Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Contention Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(sql_contention_resolver_retries{cluster=~\"$cluster\"}[5m])) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{cluster=~\"$cluster\"}[5m])) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Leaseholders, Replicas & QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "$cluster Lease Holders Per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "replicas_leaseholders{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster Replicas Per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "replicas{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lease Holder count per Node",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "replicas_leaseholders{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$cluster QPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "delete"
    }
   ]
  },
  { "title": "Hardware Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes", "label": "memory usage" }
   ],
   "targets": [
    {
     "expr": "sys_rss{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU (percentage)" }
   ],
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized{job='cockroachdb',cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Percentage Values",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized{job='cockroachdb',cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage Values",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_rss{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_query_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Combined"
    }
   ]
  },
  {
   "title": "QPS Values (Without Deletes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_query_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m])) - sum(rate(sql_delete_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Combined"
    }
   ]
  }
 ]
}