{
 "title": "Retail - CockroachDB: Runtime",
 "tags": [
  "CockroachDB",
  "VMWare"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Nodes: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Built Timestamp",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "build_timestamp{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(sys_go_allocbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "RSS: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sys_rss{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sys_goroutines{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_goroutines{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(sys_gc_pause_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pauses: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(sys_gc_pause_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(sys_cpu_user_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]) + rate(sys_cpu_sys_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cgocalls{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sys_cgocalls{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean RPC Clock Offset: $node",
   "type": "timeseries",
   "description": "Mean clock offset with other nodes as measured by cockroach.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"cockroachdb\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clock Offset: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"cockroachdb\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}