{
 "title": "Retail - Service Whisper: Central",
 "tags": [
  "Retail",
  "ServiceWhisper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(gin_request_body_total{job=\"Service Whisper\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_request_uv_total{job=\"Service Whisper\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2## Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_uri_request_total{job=\"Service Whisper\",code=~\"2.+\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "3## Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_uri_request_total{job=\"Service Whisper\",code=~\"3.+\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "4## Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_uri_request_total{job=\"Service Whisper\",code=~\"4.+\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "5## Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_uri_request_total{job=\"Service Whisper\",code=~\"5.+\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "2## request count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gin_uri_request_total{job=\"Service Whisper\",code=~\"2.*\",instance=~\"$instance\"}[$__range])) by (uri, code)",
     "legendFormat": "{{code}} -> {{uri}}"
    }
   ]
  },
  {
   "title": "Other Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(gin_uri_request_total{job=\"Service Whisper\",code!~\"2.*\",instance=~\"$instance\"}[$__range])) by (uri,code) != 0",
     "legendFormat": "{{code}} -> {{uri}}"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(gin_request_body_total{job=\"Service Whisper\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(gin_response_body_total{job=\"Service Whisper\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Average Response Time by URI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(gin_request_duration_sum{job=\"Service Whisper\",instance=~\"$instance\", uri=~\"/.+\"}[$__range])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Go Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"Service Whisper\",instance=~\"$instance\"})",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "Go Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"Service Whisper\",instance=~\"$instance\"})",
     "legendFormat": "Open File Descriptors"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"Service Whisper\",instance=~\"$instance\"})",
     "legendFormat": "Go Routines"
    }
   ]
  },
  {
   "title": "Go GC 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"Service Whisper\",quantile=\"1\",instance=~\"$instance\"})",
     "legendFormat": "GC 99th Percentile"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"Service Whisper\",instance=~\"$instance\"})",
     "legendFormat": "Go Threads"
    }
   ]
  },
  {
   "title": "Go GC 75th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"Service Whisper\",quantile=\"0.75\",instance=~\"$instance\"})",
     "legendFormat": "GC 75th Percentile"
    }
   ]
  },
  {
   "title": "Go CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"Service Whisper\",instance=~\"$instance\"}[15m]))",
     "legendFormat": "CPU Seconds"
    }
   ]
  },
  {
   "title": "Go GC 50th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"Service Whisper\",quantile=\"0.5\",instance=~\"$instance\"})",
     "legendFormat": "GC 50th Percentile"
    }
   ]
  }
 ]
}