{
 "title": "Retail - MSSQL: Central",
 "tags": [
  "MSSQL",
  "Retail"
 ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(windows_mssql_collector_success,cluster)"
    }
   },
   {
    "name": "offset",
    "label": "offset",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_mssql_collector_success{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait for Worker Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_waitstats_wait_for_the_worker_waits{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - {{item}}"
    },
    {
     "expr": "rate(windows_mssql_waitstats_wait_for_the_worker_waits{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]offset $offset) != 0",
     "legendFormat": "{{instance}} - {{item}} (offset $offset)"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_memory_committed_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} - Free Memory"
    },
    {
     "expr": "windows_memory_committed_bytes{cluster=\"$cluster\"} offset $offset",
     "legendFormat": "{{instance}} - Free Memory (offset $offset)"
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{cluster=\"$cluster\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_sqlstats_batch_requests{cluster=~\"$cluster\",instance=~\"$instance\"}[5m])!= 0",
     "legendFormat": "{{instance}} - Batch Requests/Second"
    },
    {
     "expr": "rate(windows_mssql_sqlstats_batch_requests{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Batch Requests/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_user_connections{cluster=~\"$cluster\",instance=~\"$instance\"} != 0",
     "legendFormat": "{{instance}} - User Connections"
    },
    {
     "expr": "windows_mssql_genstats_user_connections{cluster=~\"$cluster\",instance=~\"$instance\"} offset $offset != 0",
     "legendFormat": "{{instance}} - User Connections (offset $offset)"
    }
   ]
  },
  {
   "title": "Logins/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_genstats_logins{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Logins/Second"
    },
    {
     "expr": "rate(windows_mssql_genstats_logins{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Logins/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "Page Reads/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_bufman_page_reads{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Page Reads/Second"
    },
    {
     "expr": "rate(windows_mssql_bufman_page_reads{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Page Reads/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "Page Writes/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_bufman_page_writes{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Page Writes/Second"
    },
    {
     "expr": "rate(windows_mssql_bufman_page_writes{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Page Writes/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "Memory Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Page Life Expectancy/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_life_expectancy_seconds{cluster=~\"$cluster\",instance=~\"$instance\"} != 0",
     "legendFormat": "{{instance}} - Page Life Expectancy Seconds"
    },
    {
     "expr": "windows_mssql_bufman_page_life_expectancy_seconds{cluster=~\"$cluster\",instance=~\"$instance\"} offset $offset != 0",
     "legendFormat": "{{instance}} - Page Life Expectancy Seconds (offset $offset)"
    }
   ]
  },
  {
   "title": "Page Faults/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_memory_page_faults_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Page Faults/Second - {{instance}}"
    },
    {
     "expr": "rate(windows_memory_page_faults_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Page Faults/Second - {{instance}} (offset $offset)"
    }
   ]
  },
  {
   "title": "Disk Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Disk Read Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(windows_logical_disk_read_latency_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m])) by (instance) != 0",
     "legendFormat": "{{instance}} - Average Disk Read Response Time"
    },
    {
     "expr": "avg(rate(windows_logical_disk_read_latency_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset)) by (instance) != 0",
     "legendFormat": "{{instance}} - Average Disk Read Response Time (offset $offset)"
    }
   ]
  },
  {
   "title": "Average Disk Write Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(windows_logical_disk_write_latency_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m])) by (instance) != 0",
     "legendFormat": "{{instance}} - Average Disk Write Response Time"
    },
    {
     "expr": "avg(rate(windows_logical_disk_write_latency_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset)) by (instance) != 0",
     "legendFormat": "{{instance}} - Average Disk Write Response Time (offset $offset)"
    }
   ]
  },
  {
   "title": "EFFICIENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compilations/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_sqlstats_sql_compilations{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Compilations/Second"
    },
    {
     "expr": "rate(windows_mssql_sqlstats_sql_compilations{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Compilations/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "Full Scans/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_accessmethods_full_scans{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Full Scans/Second"
    },
    {
     "expr": "rate(windows_mssql_accessmethods_full_scans{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Full Scans/Second (offset $offset)"
    }
   ]
  },
  {
   "title": "Index Searches/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_mssql_accessmethods_index_searches{cluster=~\"$cluster\",instance=~\"$instance\"}[5m]) != 0",
     "legendFormat": "{{instance}} - Index Searches/Second"
    },
    {
     "expr": "rate(windows_mssql_accessmethods_index_searches{cluster=~\"$cluster\",instance=~\"$instance\"}[5m] offset $offset) != 0",
     "legendFormat": "{{instance}} - Index Searches/Second (offset $offset)"
    }
   ]
  }
 ]
}