{
 "title": "CoreDNS",
 "description": "CoreDNS dashboard, focused on latency and cache-efficiency observability.  Includes query and response time-series stack charts.   Allows user to easily select both datasource and application (kube-dns, node-local-dns).",
 "tags": [
  "DNS",
  "SRE",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(coredns_build_info{kubernetes_cluster=\"$kubernetes_cluster\"}, k8s_app)"
    }
   },
   {
    "name": "kubernetes_cluster",
    "label": "kubernetes_cluster",
    "query": {
     "query": "label_values(felix_log_errors, kubernetes_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Cache efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "pct" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m]))/sum(rate(coredns_dns_request_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m]))",
     "legendFormat": "hit rate"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m]))/sum(rate(coredns_dns_requests_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "Query latency, heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries by protocol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "total qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Queries by zone",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "total qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Responses by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "total qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode-zone}}"
    }
   ]
  },
  {
   "title": "Queries by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "total qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\", type!=\"other\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\", type!=\"other\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Responses/sec by zone and type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "total qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (rcode, zone)",
     "legendFormat": "type={{rcode}}, zone=\"{{zone}}\""
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{k8s_app=\"$application\", kubernetes_cluster=~\"$kubernetes_cluster\"}[5m])) by (rcode, zone)",
     "legendFormat": "type={{rcode}}, zone=\"{{zone}}\""
    }
   ]
  }
 ]
}