{
 "title": "Kubernetes API server",
 "description": "kubernetes api dashbord",
 "tags": [
  "kubernetes",
  "kube-apiserver"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, kubernetes_cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$cluster-apiserver\", instance=~\"$instance\",code=~\"2..\", kubernetes_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$cluster-apiserver\", instance=~\"$instance\",code=~\"3..\", kubernetes_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$cluster-apiserver\", instance=~\"$instance\",code=~\"4..\", kubernetes_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$cluster-apiserver\", instance=~\"$instance\",code=~\"5..\", kubernetes_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, cluster:apiserver_request_duration_seconds:quantile{kubernetes_cluster=\"$cluster\"})",
     "legendFormat": "{{verb}} {{ resource }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$cluster-apiserver\",instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} (RSS)"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"$cluster-apiserver\",instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} (Go)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$cluster-apiserver\",instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$cluster-apiserver\",instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Long running requests by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{verb!~\"WATCH|CONNECT\", job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}) by (verb, resource, subresource)",
     "legendFormat": "{{ verb }} {{ resource }}/{{ subresource }}"
    },
    {
     "expr": "sum(apiserver_longrunning_requests{verb!~\"WATCH|CONNECT\", job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}) by (verb, resource, subresource)",
     "legendFormat": "{{ verb }} {{ resource }}/{{ subresource }}"
    }
   ]
  },
  {
   "title": "Long running requests by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(apiserver_longrunning_requests{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current inflight requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} ({{ requestKind }}{{ request_kind }})"
    }
   ]
  },
  {
   "title": "Request Termination Rate",
   "type": "graph",
   "description": "Rate of requests which apiserver terminated in self-defense.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$cluster-apiserver\", instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"$cluster-apiserver\", instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$cluster-apiserver\", instance=~\"$instance\", kubernetes_cluster=\"$cluster\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Audit Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_audit_event_total{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Audit Error Rate",
   "type": "graph",
   "description": "audit events that failed to be audited properly",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_audit_error_total{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }} ({{ plugin }})"
    }
   ]
  },
  {
   "title": "Audit Rejected Rate",
   "type": "graph",
   "description": "apiserver requests rejected due to an error in the audit logging backend",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_audit_requests_rejected_total{job=\"$cluster-apiserver\", kubernetes_cluster=\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}