{
 "title": "SRE Kubernetes Cluster",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app",
  "SRE BF"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{kubernetes_cluster=\"$Cluster\", phase=\"Active\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(cadvisor_version_info{kubernetes_cluster=~\"$Cluster\"}, kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node!~\".*(master|build).*\", kubernetes_cluster=~\"$Cluster\"}) / sum(kube_node_status_allocatable{node!~\".*(master|build).*\",kubernetes_cluster=\"$Cluster\", resource=\"pods\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"}) / sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"}) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"}) / sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"pods\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"pods\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU namespace quota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "cores", "label": "vCPU" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"hard\",resource=\"requests.cpu\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\", kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "requests hard"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"used\",resource=\"requests.cpu\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "requests used"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"hard\",resource=\"limits.cpu\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "limits hard"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"used\",resource=\"limits.cpu\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "limits used"
    }
   ]
  },
  {
   "title": "Memory namespace quota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"hard\",resource=\"requests.memory\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "requests hard"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"used\",resource=\"requests.memory\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "requests used"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"hard\",resource=\"limits.memory\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "limits hard"
    },
    {
     "expr": "sum by (kubernetes_cluster) (kube_resourcequota{type=\"used\",resource=\"limits.memory\", kubernetes_cluster=~\"$Cluster\",node!~\".*(master|build).*\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "limits used"
    }
   ]
  },
  {
   "title": "Allocatable worker vCPU cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=\"$Cluster\", resource=\"cpu\", node!~\".*(master|build).*\"})"
    }
   ]
  },
  {
   "title": "Sum of pod CPU requests in worker nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "cores", "label": "vCPU" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", kubernetes_namespace=~\"$namespace\", resource=\"cpu\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=\"$Cluster\", resource=\"cpu\", node!~\".*(master|build).*\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Sum of containers' CPU usage in worker nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "cores", "label": "vCPU" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=\"$Cluster\" , namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Allocatable worker memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=\"$Cluster\", resource=\"memory\", node!~\".*(master|build).*\"})"
    }
   ]
  },
  {
   "title": "Sum of pod memory requests in worker nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", kubernetes_namespace=~\"$namespace\", resource=\"memory\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Sum of containers' memory usage in worker nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", instance!~\".*(master|build).*\",kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", resource=\"memory\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "CPU usage per namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{kubernetes_cluster=\"$Cluster\", node!~\".*(master|build).*\", image!=\"\"}[1m])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Resource Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespaces with significant CPU request usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(kube_resourcequota{type=\"used\",resource=\"requests.cpu\", kubernetes_cluster=~\"$Cluster\"}) by (kubernetes_namespace) > 5)",
     "legendFormat": "{{ kubernetes_namespace }}"
    }
   ]
  },
  {
   "title": "Namespaces with significant memory request usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(kube_resourcequota{type=\"used\",resource=\"requests.memory\", kubernetes_cluster=~\"$Cluster\"}) by (kubernetes_namespace) > 10 * 2^30)",
     "legendFormat": "{{ kubernetes_namespace }}"
    }
   ]
  },
  {
   "title": "CPU requests per node (all namespaces)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\"} * on (pod, container, namespace) group_left(node) kube_pod_container_resource_requests{kubernetes_cluster=\"$Cluster\", node!~\".*(master|build).*\", resource=\"cpu\"} )",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "Pods with highest cpu requests",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "topk(50, sort_desc(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", kubernetes_namespace=~\"$namespace\", resource=\"cpu\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\"}))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods with highest memory requests",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "topk(50, sort_desc(kube_pod_container_resource_requests{kubernetes_cluster=~\"$Cluster\", node!~\".*(master|build).*\", kubernetes_namespace=~\"$namespace\", resource=\"memory\"} * on (pod, container, namespace) kube_pod_container_status_running{kubernetes_cluster=~\"$Cluster\"})) / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (rate (container_network_receive_bytes_total{kubernetes_cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "-> {{ kubernetes_io_hostname }}"
    },
    {
     "expr": "- sum by (kubernetes_io_hostname) (rate (container_network_transmit_bytes_total{kubernetes_cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "<- {{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",interface!~\"cni0|flannel.1\",kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\", pod_name=~\"^$deployment-[a-z0-9]*-[a-z0-9]+$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",interface!~\"cni0|flannel.1\",kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\",  pod_name=~\"^$deployment-[a-z0-9]*-[a-z0-9]+$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", kubernetes_cluster=~\"$Cluster\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",instance=~\"^$server$\"}[1m])) by (container, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",instance=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",instance=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",container!=\"POD\",kubernetes_io_hostname=~\"^$server$\"}) by (container, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$server$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$server$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (container, pod_name)",
     "legendFormat": "-> pod: {{ pod_name }} | {{ container }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (container, pod_name)",
     "legendFormat": "<- pod: {{ pod_name }} | {{ container }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$server$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", kubernetes_cluster=\"$Cluster\" , namespace=~\"$namespace\", pod_name=~\"^$deployment-[a-z0-9-]+$\"}[1m])) by (pod_name) ",
     "legendFormat": "USAGE-{{ pod_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_cfs_throttled_seconds_total{image!=\"\", kubernetes_cluster=\"$Cluster\" , namespace=~\"$namespace\", pod_name=~\"^$deployment-[a-z0-9-]+$\"}[1m])) by (pod_name)",
     "legendFormat": "THROTTLED-{{ pod_name }}"
    },
    {
     "expr": "(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"^$deployment-[a-z0-9-]+$\", kubernetes_cluster=\"$Cluster\", resource=\"cpu\"})",
     "legendFormat": "REQUESTS-{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$deployment-[a-z0-9-]+$\", kubernetes_cluster=\"$Cluster\", resource=\"cpu\"}",
     "legendFormat": "LIMITS-{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\", pod_name=~\"^$deployment-[a-z0-9-]+$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_ephemeral_storage_usage_bytes{kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\", pod=~\"$deployment-[a-z0-9-]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_ephemeral_storage_usage_bytes{kubernetes_cluster=\"$Cluster\", namespace=~\"$namespace\", pod=~\"$deployment-[a-z0-9-]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Persistent Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of persistent volume claims",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 185 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_info{kubernetes_cluster=~\"$Cluster\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{kubernetes_cluster=~\"$Cluster\", kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claim Requests"
    }
   ]
  },
  {
   "title": "PVC requests by namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{kubernetes_cluster=~\"$Cluster\"}) by (kubernetes_namespace))",
     "legendFormat": "{{ kubenetes_namespace }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes' status (cluster-wide)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{kubernetes_cluster=~\"$Cluster\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims' status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{kubernetes_cluster=~\"$Cluster\", kubernetes_namespace=~\"$namespace\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg without (kubernetes_io_hostname, instance) (kubelet_volume_stats_used_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "avg without (kubernetes_io_hostname, instance) (kubelet_volume_stats_capacity_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "avg without (kubernetes_io_hostname, instance) (\nkubelet_volume_stats_used_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"} * 100)"
    }
   ]
  },
  {
   "title": "PVC Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 221 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg without(kubernetes_io_hostname, instance) (kubelet_volume_stats_used_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{kubernetes_cluster=~\"$Cluster\", namespace=~\"$namespace\"} * 100)",
     "legendFormat": "{{persistentvolumeclaim}}, {{namespace}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 233 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\", kubernetes_cluster=~\"$Cluster\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 237 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 237 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Jobs Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\", kubernetes_cluster=~\"$Cluster\"})"
    }
   ]
  }
 ]
}