{
 "title": "Unified Dashboard",
 "tags": [ "SRE BF" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": ".+(v3|v2|fp|hz).*, .+v2.*, .+(v3|fp|hz).*, gb1-li-beunityv2, gb1-li-feunityv2, gb4-li-beunityv2, gb4-li-feunityv2, gb1-li-feunityv3, gb1-li-beunityv3, gb4-li-feunityv3, gb4-li-beunityv3, gb1-li-feunityhz, gb1-li-feunityfp, gb4-li-feunityhz, gb4-li-feunityfp"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<<!DOCTYPE html>\n<html>\n<style>\ntable, th, td {\n  border:1px solid black;\n}\n</style>\n<body>\n\n<h4 align=\"center\">Quick Links to Dashboards</h2>\n\n<table style=\"width:100%\">\n  <tr>\n    <th>K8s in-depth</th>\n    <th>ETCD</th>\n    <th>API Server</th>\n    <th>Core DNS</th>\n    <th>CPU Throttling</th>\n    <th>Kibana</th>\n    <th>Prometheus</th>\n    <th>HA Proxy</th>\n    <th>Tenant Resource Usage</th>  \n  </tr>\n\n\n  <tr>\n    <td> \n      <a href= \"https://grafana.io.thehut.local/d/4XuMd2Iiz/sre-kubernetes-cluster?orgId=1&refresh=30s&from=now-1h&to=now&var-datasource=GB4%20Live%20BEUnity%20Devops%20Prometheus&var-Cluster=gb4-li-beunityv2&var-namespace=All&var-deployment=All&var-server=gb4-li-beunityv2build-001\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/4XuMd2Iiz/sre-kubernetes-cluster?orgId=1&refresh=30s&from=now-1h&to=now&var-datasource=GB4%20Live%20FEUnity%20Devops%20Prometheus&var-Cluster=gb4-li-feunityv2&var-namespace=All&var-deployment=All&var-server=gb4-li-feunityv2build-001\" target=\"_blank\">GB4-FE</a><br>\n       <a href=\"https://grafana.io.thehut.local/d/4XuMd2Iiz/sre-kubernetes-cluster?orgId=1&refresh=30s&from=now-1h&to=now&var-datasource=GB1%20Live%20BEUnity%20Devops%20Prometheus&var-Cluster=gb1-li-beunityv2&var-namespace=All&var-deployment=All&var-server=gb1-li-beunityv2build-001\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n       <a href=\"https://grafana.io.thehut.local/d/4XuMd2Iiz/sre-kubernetes-cluster?orgId=1&refresh=30s&from=now-1h&to=now&var-datasource=GB1%20Live%20FEUnity%20Devops%20Prometheus&var-Cluster=gb1-li-feunityv2&var-namespace=All&var-deployment=All&var-server=gb1-li-feunityv2build-001\" target=\"_blank\">GB1-FE</a>\n      \n    </td>\n  \n    <td>\n      <a href=\"https://grafana.io.thehut.local/d/u5reMx7iz/devops-etcd?orgId=1&refresh=30s&from=now-1h&to=now&var-cluster=gb4-li-beunityv2etcd&var-datasource=GB4%20Live%20BEUnity%20Devops%20Prometheus\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/u5reMx7iz/devops-etcd?orgId=1&refresh=30s&from=now-1h&to=now&var-cluster=gb4-li-feunityv2etcd&var-datasource=GB4%20Live%20FEUnity%20Devops%20Prometheus\" target=\"_blank\" >GB4-FE</a><br>\n      <a href=\"https://grafana.io.thehut.local/d/u5reMx7iz/devops-etcd?orgId=1&refresh=30s&from=now-1h&to=now&var-cluster=gb1-li-beunityv2etcd&var-datasource=GB1%20Live%20BEUnity%20Devops%20Prometheus\" target=\"_blank\" >GB1-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/u5reMx7iz/devops-etcd?orgId=1&refresh=30s&from=now-1h&to=now&var-cluster=gb1-li-feunityv2etcd&var-datasource=GB1%20Live%20FEUnity%20Devops%20Prometheus\" target=\"_blank\" >GB1-FE</a>\n    </td>\n\n    <td>\n      <a href=\"https://gb1.grafana.io.thehut.local/goto/a2_AXm4Sg?orgId=1\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s&var-datasource=GB4%20Live%20FEUnity%20Devops%20Prometheus&var-cluster=gb4-li-feunityv2&var-instance=All\" target=\"_blank\">GB4-FE</a><br>\n      <a href=\"https://grafana.io.thehut.local/d/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s&var-datasource=GB1%20Live%20BEUnity%20Devops%20Prometheus&var-cluster=gb1-li-beunityv2&var-instance=All\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s&var-datasource=GB1%20Live%20FEUnity%20Devops%20Prometheus&var-cluster=gb1-li-feunityv2&var-instance=All\" target=\"_blank\">GB1-FE</a>\n    </td>\n\n    <td>\n      <a href=\"https://grafana.io.thehut.local/d/Yr1oUjuZz/coredns?orgId=1&var-datasource=GB4%20Live%20BEUnity%20Devops%20Prometheus&var-application=kube-dns&var-kubernetes_cluster=gb4-li-beunityv2\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/Yr1oUjuZz/coredns?orgId=1&var-datasource=GB4%20Live%20FEUnity%20Devops%20Prometheus&var-application=kube-dns&var-kubernetes_cluster=gb4-li-feunityv2\" target=\"_blank\">GB4-FE</a><br>\n      <a href=\"https://grafana.io.thehut.local/d/Yr1oUjuZz/coredns?orgId=1&var-datasource=GB1%20Live%20BEUnity%20Devops%20Prometheus&var-application=kube-dns&var-kubernetes_cluster=gb1-li-beunityv2\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/Yr1oUjuZz/coredns?orgId=1&var-datasource=GB1%20Live%20FEUnity%20Devops%20Prometheus&var-application=kube-dns&var-kubernetes_cluster=gb1-li-feunityv2\" target=\"_blank\">GB1-FE</a>\n    </td>\n\n    <td>\n      <a href=\"https://grafana.io.thehut.local/d/5nq9N3Bik/sre-throttling-monitoring?orgId=1&var-datasource=GB4%20Live%20BEUnity%20Devops%20Prometheus&var-Cluster=gb4-li-beunityv2&var-namespace=All&var-deployment=All&var-server=All&var-pod=All\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/5nq9N3Bik/sre-throttling-monitoring?orgId=1&var-datasource=GB4%20Live%20FEUnity%20Devops%20Prometheus&var-Cluster=gb4-li-feunityv2&var-namespace=All&var-deployment=All&var-server=All&var-pod=All\" target=\"_blank\">GB4-FE</a><br>\n      <a href=\"https://grafana.io.thehut.local/d/5nq9N3Bik/sre-throttling-monitoring?orgId=1&var-datasource=GB1%20Live%20BEUnity%20Devops%20Prometheus&var-Cluster=gb1-li-beunityv2&var-namespace=All&var-deployment=All&var-server=All&var-pod=All\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/5nq9N3Bik/sre-throttling-monitoring?orgId=1&var-datasource=GB1%20Live%20FEUnity%20Devops%20Prometheus&var-Cluster=gb1-li-feunityv2&var-namespace=All&var-deployment=All&var-server=All&var-pod=All\" target=\"_blank\">GB1-FE</a>\n    </td>\n\n    <td>\n      <a href=\"https://gb4.manifest.io.thehut.local/app/kibana#/discover\" target=\"_blank\">GB4</a>&nbsp&nbsp\n      <a href=\"https://gb1.manifest.io.thehut.local/app/kibana#/discover\" target=\"_blank\">GB1</a>\n    </td>\n\n    <td> \n      <a href=\"http://gb4-li-devopsprometheus-001.io.thehut.local/alerts\" target=\"_blank\">GB4-DevOps</a>&nbsp&nbsp\n      <a href=\"http://gb4-li-beunity-prometheus.io.thehut.local/alerts\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"http://gb4-li-feunity-prometheus.io.thehut.local/alerts\" target=\"_blank\">GB4-FE</a>&nbsp&nbsp\n      <a href=\"http://gb4-li-feunity-nginxprometheus.io.thehut.local/alerts\" target=\"_blank\">GB4-Nginx</a><br>\n      <a href=\"http://gb1-li-devopsprometheus-001.io.thehut.local/alerts\" target=\"_blank\">GB1-DevOps</a>&nbsp&nbsp\n      <a href=\"http://gb1-li-beunity-prometheus.io.thehut.local/alerts\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n      <a href=\"http://gb1-li-feunity-prometheus.io.thehut.local/alerts\" target=\"_blank\">GB1-FE</a>&nbsp&nbsp\n      <a href=\"http://gb1-li-feunity-nginxprometheus.io.thehut.local/alerts\" target=\"_blank\">GB1-Nginx</a>\n    </td>\n    <td>\n      <a href=\"https://grafana.io.thehut.local/d/CFIoAK-Wz/haproxy?orgId=1&refresh=30s&var-dc=GB4%20Live%20BEUnity%20Devops%20Prometheus&var-host=gb4-li-beunityv2haproxy-001.io.thehut.local&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s\" target=\"_blank\">GB4-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/CFIoAK-Wz/haproxy?orgId=1&refresh=30s&var-dc=GB4%20Live%20FEUnity%20Devops%20Prometheus&var-host=gb4-li-feunityv2haproxy-001.io.thehut.local&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s\" target=\"_blank\">GB4-FE</a><br>\n      <a href=\"https://grafana.io.thehut.local/d/CFIoAK-Wz/haproxy?orgId=1&refresh=30s&var-dc=GB1%20Live%20BEUnity%20Devops%20Prometheus&var-host=gb1-li-beunityv2haproxy-001.io.thehut.local&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s\" target=\"_blank\">GB1-BE</a>&nbsp&nbsp\n      <a href=\"https://grafana.io.thehut.local/d/CFIoAK-Wz/haproxy?orgId=1&refresh=30s&var-dc=GB1%20Live%20FEUnity%20Devops%20Prometheus&var-host=gb1-li-feunityv2haproxy-001.io.thehut.local&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s\" target=\"_blank\">GB1-FE</a>   \n    </td>\n    <td>\n      <a href=\"https://grafana.io.thehut.local/d/bed0666e-4342-4d04-b3b9-1945085dc080/unity-cluster-resource-usage?orgId=1&var-Cluster=gb1-li-beunityv2&from=now-6h&to=now\" target=\"_blank\">Unity Resource Usage</a>\n    </td>\n  </tr>\n</table>\n</body>\n</html>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Masters Down (Backend)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_server_up{job=~\"${cluster}haproxy\"}) - sum(haproxy_server_up{job=~\"${cluster}haproxy\"})",
     "legendFormat": "{{ server }}"
    },
    {
     "expr": "haproxy_server_up{job=~\"${cluster}haproxy\"} != 1",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "count(haproxy_server_up{job=~\"${cluster}haproxy\"}) - sum(haproxy_server_up{job=~\"${cluster}haproxy\"})",
     "legendFormat": "{{ server }}"
    },
    {
     "expr": "haproxy_server_up{job=~\"${cluster}haproxy\"} != 1",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Nodes Not Ready (Backend)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{kubernetes_cluster=~\"$cluster\", condition=\"Ready\", status=\"false\"} == 1)"
    },
    {
     "expr": "count(kube_node_status_condition{kubernetes_cluster=~\"$cluster\", condition=\"Ready\", status=\"false\"} == 1)"
    }
   ]
  },
  {
   "title": "Masters Down (Front End)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_server_up{job=~\"${cluster}haproxy\"}) - sum(haproxy_server_up{job=~\"${cluster}haproxy\"})",
     "legendFormat": "{{ server }}"
    },
    {
     "expr": "haproxy_server_up{job=~\"${cluster}haproxy\"} != 1",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "\r\ncount(haproxy_server_up{job=~\"${cluster}haproxy\"}) - sum(haproxy_server_up{job=~\"${cluster}haproxy\"})",
     "legendFormat": "{{ server }}"
    },
    {
     "expr": "haproxy_server_up{job=~\"${cluster}haproxy\"} != 1",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Nodes Not Ready (Frontend)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{kubernetes_cluster=~\"${cluster}\", condition=\"Ready\", status=\"false\"} == 1)"
    },
    {
     "expr": "count(kube_node_status_condition{kubernetes_cluster=~\"$cluster\", condition=\"Ready\", status=\"false\"} == 1)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{kubernetes_cluster=~\"$cluster\", image!=\"\"}[1m])) by (node) / on (node) kube_node_status_allocatable{resource=\"cpu\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{kubernetes_cluster=~\"$cluster\", image!=\"\"}[1m])) by (node) / on (node) kube_node_status_allocatable{resource=\"cpu\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{kubernetes_cluster=~\"$cluster\", image!=\"\"}[1m])) by (node) / on (node) kube_node_status_allocatable{resource=\"cpu\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{kubernetes_cluster=~\"$cluster\", image!=\"\"}[1m])) by (node) / on (node) kube_node_status_allocatable{resource=\"cpu\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{kubernetes_cluster=~\"$cluster\", image!=\"\"}) by (node) / on (node) kube_node_status_allocatable{resource=\"memory\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{kubernetes_cluster=~\"$cluster\", image!=\"\"}) by (node) / on (node) kube_node_status_allocatable{resource=\"memory\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{kubernetes_cluster=~\"$cluster\", image!=\"\"}) by (node) / on (node) kube_node_status_allocatable{resource=\"memory\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{kubernetes_cluster=~\"$cluster\", image!=\"\"}) by (node) / on (node) kube_node_status_allocatable{resource=\"memory\", kubernetes_cluster=~\"$cluster\"} * 100) ",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Worker CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"cpu\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"cpu\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"cpu\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"cpu\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    }
   ]
  },
  {
   "title": "Worker Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"memory\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"memory\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"memory\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (kubernetes_cluster)",
     "legendFormat": "Used - {{kubernetes_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{kubernetes_cluster=~\"$cluster\", node!~\".*(master|build).*\", resource=\"memory\"}) by (kubernetes_cluster)",
     "legendFormat": "Allocatable - {{kubernetes_cluster}}"
    }
   ]
  },
  {
   "title": "Worker CPU usage by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "cores", "label": "vCPU" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}[1m])) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Worker Memory usage by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    },
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{image!=\"\", node!~\".*(master|build).*\", kubernetes_cluster=~\"$cluster\"}) by (namespace, kubernetes_cluster)) by (kubernetes_cluster)",
     "legendFormat": "{{kubernetes_cluster}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "ETCD Peer roundtrip time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "ETCD Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(etcd_server_leader_changes_seen_total{job=~\"${cluster}etcd\"}[1m])",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "irate(etcd_server_leader_changes_seen_total{job=~\"${cluster}etcd\"}[1m])",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "irate(etcd_server_leader_changes_seen_total{job=~\"${cluster}etcd\"}[1m])",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "irate(etcd_server_leader_changes_seen_total{job=~\"${cluster}etcd\"}[1m])",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "ETCD Disk Sync Duration ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} DB fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{ source }} DB fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} DB fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} DB fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"${cluster}etcd\"}[5m])) by (source, le))",
     "legendFormat": "{{source}} WAL fsync"
    }
   ]
  },
  {
   "title": "APIServer Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (kubernetes_cluster) (cluster:apiserver_request_duration_seconds:quantile{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "{{ kubernetes_cluster }}"
    },
    {
     "expr": "max by (kubernetes_cluster) (cluster:apiserver_request_duration_seconds:quantile{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "{{ kubernetes_cluster }}"
    },
    {
     "expr": "max by (kubernetes_cluster) (cluster:apiserver_request_duration_seconds:quantile{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "{{ kubernetes_cluster }}"
    },
    {
     "expr": "max by (kubernetes_cluster) (cluster:apiserver_request_duration_seconds:quantile{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "{{ kubernetes_cluster }}"
    }
   ]
  }
 ]
}