{
 "title": "Retail - PostgreSQL Central",
 "description": "Dashbord works with postgres_exporter for prometheus",
 "tags": [
  "Postgres",
  "VMWare"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"postgresql\"},cluster)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[5m]) *1000 / on() group_left() max(pg_settings_max_worker_processes{cluster=\"$cluster\"}), \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(process_resident_memory_bytes{cluster=\"$cluster\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} Resident Mem"
    },
    {
     "expr": "label_replace(rate(process_virtual_memory_bytes{cluster=\"$cluster\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(process_open_fds{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} Open FD"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", cluster=~\"$cluster\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(pg_stat_database_xact_commit{cluster=\"$cluster\", datname=~\"$datname\"}[5m]) !=0, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} {{datname}} commits"
    },
    {
     "expr": "label_replace(irate(pg_stat_database_xact_rollback{cluster=\"$cluster\", datname=~\"$datname\"}[5m]) !=0, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} {{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(pg_locks_count{datname=~\"$datname\", cluster=~\"$cluster\", mode=~\"$mode\"} !=0, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} {{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Replication WAL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "label_replace(pg_replication_lag{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}