{
 "title": "Retail - PostgreSQL: Cluster Summary",
 "tags": [
  "Postgres",
  "Retail"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"postgresql\"},cluster)"
    }
   },
   {
    "name": "datacentre",
    "label": "Datacentre",
    "query": {
     "query": "label_values(up{job=\"postgresql\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "By Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(irate(pg_stat_database_xact_commit{cluster=~\"$cluster\",instance=~\"$datacentre-.*$\"}[5m]) !=0, \"node\", \"$1\", \"instance\", \"(.*?):.*\"), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (cluster, datacentre)",
     "legendFormat": "{{datacentre}}-{{cluster}}"
    },
    {
     "expr": "label_replace(irate(pg_stat_database_xact_rollback{cluster=\"$cluster\", datname=~\"$datname\"}[5m]) !=0, \"node\", \"$1\", \"instance\", \"(.*?):.*\")",
     "legendFormat": "{{node}} {{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace((sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))), \"node_name\", \"$1\", \"instance\", \"^([^:]+):.*$\") * on(node_name) group_left(cluster) label_replace(patroni_master{job=\"postgresql\"}, \"node_name\", \"$1\", \"instance\", \"^([^:]+):.*$\")) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(rate(process_resident_memory_bytes{cluster=~\"$cluster\",instance=~\"$datacentre-.*$\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*?):.*\"), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\") + label_replace(label_replace(rate(process_virtual_memory_bytes{cluster=~\"$cluster\",instance=~\"$datacentre-.*$\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*?):.*\"), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (cluster,datacentre)",
     "legendFormat": "{{datacentre}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Replication WAL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(label_replace(label_replace(pg_replication_lag{cluster=~\"$cluster\",instance=~\"$datacentre-.*$\"}, \"node\", \"$1\", \"instance\", \"(.*?):.*\"), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (cluster,datacentre)",
     "legendFormat": "{{datacentre}}-{{cluster}}"
    }
   ]
  }
 ]
}