{
 "title": "THG - Central",
 "tags": [
  "Kubernetes",
  "VMWare",
  "CockroachDB",
  "Postgres",
  "MSSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Alerts" } },
  {
   "title": "CockroachDB Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Couchbase Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {}
   ]
  },
  { "title": "Retail DC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "options": { "content": "# CockroachDB" } },
  {
   "title": "CockroachDB Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sys_uptime{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CockroachDB Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "count(label_replace(sys_uptime{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(sys_rss{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(label_replace(sys_cpu_combined_percent_normalized{job='cockroachdb',instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CockroachDB Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sys_uptime{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CockroachDB Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 } },
  {
   "title": "Leaseholders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "sum(label_replace(replicas_leaseholders{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 23 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(sql_select_count{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre) + \nsum(label_replace(rate(sql_insert_count{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre) + \nsum(label_replace(rate(sql_update_count{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre) + \nsum(label_replace(rate(sql_delete_count{job=\"cockroachdb\",instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clock Skew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(label_replace(clock_offset_meannanos{job='cockroachdb',instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 }, "options": { "content": "# Postgres" } },
  {
   "title": "Postgres Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(pg_up{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_replace(pg_stat_activity_count{job='postgresql',instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(process_resident_memory_bytes{job='postgresql',instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(label_replace(rate(process_cpu_seconds_total{job=\"postgresql\",instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]) * 10000, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(pg_up{}) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CockroachDB Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 } },
  {
   "title": "Replication WAL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(pg_replication_lag{job='postgresql',instance=~\"(de1|gb1|gb4|gb5).+\"}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 }, "options": { "content": "# Couchbase" } },
  {
   "title": "Couchbase Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(couchbase::node_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(couchbase_bucket_stats_misses{instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(couchbase_bucket_stats_mem_actual_used_bytes{instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 51 },
   "targets": [
    {
     "expr": "avg(label_replace(couchbase_bucket_stats_cpu_utilization_rate{instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Couchbase Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(couchbase_cluster_up{}) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CockroachDB Dashboards", "type": "dashlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 59 } },
  {
   "title": "Operations per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(couchbase_bucket_basicstats_opspersec{instance=~\"(de1|gb1|gb4|gb5).+\"}, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Couchbase Item Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(couchbase_bucket_basicstats_itemcount)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 }, "options": { "content": "# MSSQL" } },
  {
   "title": "MSSQL Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(windows_mssql_collector_success{collector=\"databases\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Disk Read Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(label_replace(rate(windows_logical_disk_read_latency_seconds_total{}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{datacentre}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(windows_memory_committed_bytes, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{datacentre}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(label_replace(100 - (irate(windows_cpu_time_total{mode=\"idle\"}[2m])) * 100, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{datacentre}}"
    }
   ]
  },
  {
   "title": "MSSQL Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group (windows_mssql_collector_success) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MSSQL Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 77 } },
  {
   "title": "User Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 77 },
   "targets": [
    {
     "expr": "sum(label_replace(windows_mssql_genstats_user_connections, \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{datacentre}}"
    }
   ]
  },
  {
   "title": "Batch Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 77 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(windows_mssql_sqlstats_batch_requests{}[5m]), \"datacentre\", \"$1\", \"instance\", \"^([^-]+)-.*$\")) by (datacentre)",
     "legendFormat": "{{datacentre}}"
    }
   ]
  },
  { "title": "ICE Region Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 }, "options": { "content": "# CockroachDB" } },
  {
   "title": "CockroachDB Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sys_uptime{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CockroachDB Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 88 },
   "targets": [
    {
     "expr": "count(sys_uptime{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{job='cockroachdb',instance!~\"(de1|gb1|gb4|gb5).+\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sys_cpu_combined_percent_normalized{job='cockroachdb',instance!~\"(de1|gb1|gb4|gb5).+\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CockroachDB Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sys_uptime{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CockroachDB Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 96 } },
  {
   "title": "Leaseholders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 96 },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 96 },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}[5m])) by (region) + \nsum(rate(sql_insert_count{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}[5m])) by (region) + \nsum(rate(sql_update_count{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}[5m])) by (region) + \nsum(rate(sql_delete_count{job=\"cockroachdb\",instance!~\"(de1|gb1|gb4|gb5).+\"}[5m])) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clock Skew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(clock_offset_meannanos{job='cockroachdb',instance!~\"(de1|gb1|gb4|gb5).+\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 }, "options": { "content": "# Postgres" } },
  {
   "title": "Postgres Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(cnpg_collector_up{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 106 },
   "targets": [
    {
     "expr": "sum(cnpg_backends_total{}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*postgres.*\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 106 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\".*postgres.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(cnpg_collector_up{}) by (cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postgres Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 114 } },
  {
   "title": "Replication WAL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 114 },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_replication_lag{}[5m])) by (region)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}