{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datacentre", "label": "DataCentre", "query": { "query": "label_values(DataCentre)" } },
   { "name": "servicetype", "label": "Service Type", "query": { "query": "label_values(ServiceType)" } }
  ]
 },
 "panels": [
  { "title": "Multi DC Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Active",
   "type": "bargauge",
   "description": "A percentage of multi-DC database clusters that have something running from each DC - Active = Might have impact",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusterActive\"}) by (DataCentre) / sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusters\"}) by (DataCentre)",
     "legendFormat": "{{DataCentre}}"
    }
   ]
  },
  {
   "title": "Service Primary",
   "type": "bargauge",
   "description": "The Database cluster is running from a node in this DC, maintenance will have impact",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumSvcClusterPrimary\"}) by (DataCentre) / sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusters\"}) by (DataCentre)",
     "legendFormat": "{{DataCentre}}"
    }
   ]
  },
  {
   "title": "OS Primary",
   "type": "bargauge",
   "description": "WSFC Role is running from this DC",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumOSClusterPrimary\"}) by (DataCentre) / sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusters\"}) by (DataCentre)",
     "legendFormat": "{{DataCentre}}"
    }
   ]
  },
  {
   "title": "Service Unknown",
   "type": "bargauge",
   "description": "Unable to determine where the workload is running from, requires manual review",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusterUnknown\"}) by (DataCentre) / sum(serviceinsight_datacentre_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"NumClusters\"}) by (DataCentre)",
     "legendFormat": "{{DataCentre}}"
    }
   ]
  },
  {
   "title": "Primary Services",
   "type": "timeseries",
   "description": "Service Currently Running from this DC",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(serviceinsight_node_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"IsServicePrimary\",ServiceType=~\"$servicetype\"}) by (ServiceName,DataCentre) > 0",
     "legendFormat": "{{DataCentre}}-{{ServiceName}}"
    }
   ]
  },
  {
   "title": "OS Primary",
   "type": "timeseries",
   "description": "WSFC Role running from this DC",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(serviceinsight_node_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"IsOSPrimary\",ServiceType=~\"$servicetype\"}) by (ServiceName,DataCentre) > 0",
     "legendFormat": "{{DataCentre}}-{{ServiceName}}"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(serviceinsight_node_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"IsActiveNode\",ServiceType=~\"$servicetype\"}) by (ServiceName,DataCentre) > 0",
     "legendFormat": "{{DataCentre}}-{{ServiceName}}"
    }
   ]
  },
  {
   "title": "Unknown Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(serviceinsight_node_status{IsMultiDC=\"1\",DataCentre=~\"$datacentre\",type=\"IsUnknownStatus\",ServiceType=~\"$servicetype\"}) by (ServiceName,DataCentre) > 0",
     "legendFormat": "{{DataCentre}}-{{ServiceName}}"
    }
   ]
  }
 ]
}