{
 "title": "Retail - Couchbase: Central",
 "description": "Dynamic monitoring for Couchbase nodes",
 "tags": [
  "Couchbase",
  "Retail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(couchbase_cluster_storagetotals_ram_total_bytes{job=\"couchbase\"},instance)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(couchbase_bucket_stats_curr_items{instance=~\"$cluster-...:9420\",job=\"couchbase\"}, bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Balanced",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(couchbase_cluster_balanced{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalance Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(couchbase_task_rebalance_progress{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compacting Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(couchbase_task_compacting_progress{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$bucket RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * (sum by (bucket) (couchbase_bucket_basicstats_memused_bytes{instance=~\"$cluster-...:9420\"})) / sum by (bucket) (couchbase_bucket_stats_ep_max_size_bytes{instance=~\"$cluster-...:9420\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster HDD usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(couchbase_cluster_storagetotals_hdd_usedbydata_bytes{instance=~\"$cluster-...:9420\"}) / sum(couchbase_cluster_storagetotals_hdd_total_bytes{instance=~\"$cluster-...:9420\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(couchbase::node_count{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total OPS -  $bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "bucket",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(couchbase_bucket_basicstats_opspersec{instance=~\"$cluster-...:9420\",bucket=\"$bucket\"})",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Cluster average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg ((sum by(instance) (irate(node_cpu_seconds_total{cluster_name=\"$cluster\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{cluster_name=\"$cluster\"}[$__rate_interval])))))",
     "legendFormat": "50th"
    },
    {
     "expr": "max ((sum by(instance) (irate(node_cpu_seconds_total{cluster_name=\"$cluster\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{cluster_name=\"$cluster\"}[$__rate_interval])))))",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Ops per second $bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "bucket",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_basicstats_opspersec{instance=~\"$cluster-...:9420\",bucket=\"$bucket\"}",
     "legendFormat": "{{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Cluster average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{cluster_name=\"$cluster\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{cluster_name=\"$cluster\"}[$__rate_interval]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Gets / Sets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket) (couchbase_bucket_stats_cmd_set{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "Set {{instance}} {{bucket}}"
    },
    {
     "expr": "sum by (bucket) (couchbase_bucket_stats_cmd_get{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "Get {{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Evictions (per node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_evictions{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_misses{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Memory for $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Bucket Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (bucket) (couchbase_bucket_stats_mem_actual_used_bytes{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (couchbase_bucket_basicstats_itemcount{instance=~\"$cluster-...:9420\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls to disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_basicstats_diskfetches{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Compacting ($bucket)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "couchbase_bucket_couch_views_fragmentation{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Compaction Progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "couchbase_task_compacting_progress{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Rebalance Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_task_rebalance_progress{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Replication",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_dcp_replicas{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} {{bucket}} "
    }
   ]
  },
  {
   "title": "XDCR $cluster - $bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Items Sent / Remaining",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (target) (couchbase_task_xdcr_changes_left{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"})",
     "legendFormat": "{{target}} Items remaining"
    },
    {
     "expr": "sum by (target) (rate(couchbase_task_xdcr_docs_written{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}[10m]))",
     "legendFormat": "{{target}} Items sent"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_bytes{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backlog Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_backlog_size{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}} Backlog size"
    }
   ]
  },
  {
   "title": "DCP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_dcp_xdcr_connections{bucket=~\"$bucket\",instance=~\"$cluster-...:9420\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Scrape times ($bucket)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape duration (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "couchbase_node_scrape_duration_seconds{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "couchbase_cluster_index_memory_quota_bytes{instance=~\"$cluster-...:9420\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(couchbase_cluster_index_memory_quota_bytes{instance=~\"$cluster-...:9420\"})"
    }
   ]
  }
 ]
}