{
 "title": "CockroachDB: Queues",
 "tags": [ "CockroachDB" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Queue Processing Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_failure{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_process_failure{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_process_failure{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_process_failure{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_process_failure{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_process_failure{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_process_failure{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_process_failure{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    }
   ]
  },
  {
   "title": "Queue Processing Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_processingnanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    }
   ]
  },
  {
   "title": "Replica GC Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_info_transactionspangccommitted{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_gc_info_transactionspangcpending{ cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicate_removedeadreplica{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    }
   ]
  },
  {
   "title": "Replication Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_replicate_process_success{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_pending{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicate_addreplica{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Added / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removereplica{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removedeadreplica{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Dead Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removelearnerreplica{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Learner Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_rebalancereplica{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Rebalanced / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_transferlease{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Leases Transferred / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_purgatory{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas in Purgatory"
    }
   ]
  },
  {
   "title": "Split Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_split_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_split_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Merge Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_merge_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_merge_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "GC Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_gc_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Log Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_raftlog_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_raftlog_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Snapshot Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_raftsnapshot_process_success{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Consistency Checker Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_consistency_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(queue_consistency_pending{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Time Series Maintenance Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_tsmaintenance_process_success{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_pending{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  }
 ]
}