{
 "title": "CockroachDB: Slow Requests",
 "tags": [ "CockroachDB" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Slow Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_raft{cluster=\"$cluster\"})",
     "legendFormat": "Slow Raft Proposals"
    }
   ]
  },
  {
   "title": "Slow Lease Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_lease{cluster=\"$cluster\"})",
     "legendFormat": "Slow Lease Acquisitions"
    }
   ]
  },
  {
   "title": "Slow DistSender RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_distsender{cluster=\"$cluster\"})",
     "legendFormat": "Slow DistSender RPCs"
    }
   ]
  },
  {
   "title": "Slow Latch Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_latch{cluster=\"$cluster\"})",
     "legendFormat": "Slow Latch Acquisitions"
    }
   ]
  }
 ]
}