{
 "title": "CockroachDB: Distributed",
 "tags": [ "CockroachDB" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_batches{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Batch"
    },
    {
     "expr": "sum(rate(distsender_batches_partial{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Partial Batches"
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent{ cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RPCs Sent"
    },
    {
     "expr": "sum(rate(distsender_rpc_sent_local{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Local Fast-path"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent_nextreplicaerror{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replica Errors"
    },
    {
     "expr": "sum(rate(distsender_errors_notleaseholder{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Not Lease Holder Errors"
    }
   ]
  },
  {
   "title": "KV Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_commits{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(rate(txn_commits1PC{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Fast-path Commited"
    },
    {
     "expr": "sum(rate(txn_aborts{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    }
   ]
  },
  {
   "title": "KV Transaction Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_restarts_writetooold{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write Too Old"
    },
    {
     "expr": "sum(rate(txn_restarts_writetoooldmulti{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write Too Old (multiple)"
    },
    {
     "expr": "sum(rate(txn_restarts_serializable{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Forwarded Timestamp (iso=serializable)"
    },
    {
     "expr": "sum(rate(txn_restarts_asyncwritefailure{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Async Consensus Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_readwithinuncertainty{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read Within Uncertainty Interval"
    },
    {
     "expr": "sum(rate(txn_restarts_txnaborted{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(txn_restarts_txnpush{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Push Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_unknown{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "KV Transactional Durations: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(txn_durations_bucket{cluster=~\"$cluster\",pod=~\"$node\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Transaction Durations: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(txn_durations_bucket{cluster=~\"$cluster\",pod=~\"$node\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 99th percentile ",
   "type": "timeseries",
   "description": "The 99th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(liveness_heartbeatlatency_bucket{ cluster=\"$cluster\",pod=~\"$node\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(liveness_heartbeatlatency_bucket{ cluster=\"$cluster\",pod=~\"$node\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}