{
 "title": "CRDB Console: Changefeeds",
 "tags": [ "CockroachDB" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Max Changefeed Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_max_behind_nanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Max Changefeed Latency"
    }
   ]
  },
  {
   "title": "Sink Byte Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_bytes{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Emitted Bytes"
    }
   ]
  },
  {
   "title": "Changefeed Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jobs_changefeed_resume_retry_error{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Retryable Errors"
    }
   ]
  },
  {
   "title": "Sink Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    },
    {
     "expr": "sum(rate(changefeed_flushes{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Sink Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Message Emit Time"
    },
    {
     "expr": "sum(rate(changefeed_flush_nanos{cluster=\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Flush Time"
    }
   ]
  }
 ]
}