{
 "title": "CRDB Console: Replication",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(ranges{cluster=\"$cluster\",pod=~\"$node\"})) by (pod)",
     "legendFormat": "Ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Leaders"
    },
    {
     "expr": "sum(sum(replicas_leaseholders{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Lease Holders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Leaders w/o Lease"
    },
    {
     "expr": "sum(sum(ranges_unavailable{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Under-replicated"
    },
    {
     "expr": "sum(sum(ranges_overreplicated{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Over-replicated"
    }
   ]
  },
  {
   "title": "Range Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Splits"
    },
    {
     "expr": "sum(sum(rate(range_merges{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Merges"
    },
    {
     "expr": "sum(sum(rate(range_adds{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Removes"
    },
    {
     "expr": "sum(sum(rate(leases_transfers_success{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_lease_transfers{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Load-based Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_range_rebalances{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])) by (pod))",
     "legendFormat": "Load-based Range Rebalances"
    }
   ]
  },
  {
   "title": "Replicas per Store",
   "type": "timeseries",
   "description": "The number of replicas on each store.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",pod=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leaseholders per Store",
   "type": "timeseries",
   "description": "The number of leaseholder replicas on each store. A leaseholder replica is the one that receives and coordinates all read and write requests for its range.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",pod=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Queries per Store",
   "type": "timeseries",
   "description": "Exponentially weighted moving average of the number of KV batch requests processed by leaseholder replicas on each store per second. Tracks roughly the last 30 minutes of requests. Used for load-based rebalancing decisions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rebalancing_queriespersecond{cluster=\"$cluster\",pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logical Bytes per Store",
   "type": "timeseries",
   "description": "Number of logical bytes stored in [key-value pairs](https://www.cockroachlabs.com/docs/v21.1/architecture/distribution-layer.html#table-data) on each node.\n\nThis includes historical and deleted data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "totalbytes{cluster=\"$cluster\",pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Quiescence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))  ",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{cluster=\"$cluster\",pod=~\"$node\"}) by (pod))",
     "legendFormat": "Quiescent"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_voter{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Voters)"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_initial{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Initial Upreplication)"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_initial{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Non-Voters)"
    },
    {
     "expr": "sum(rate(replicas_reserved{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Reserved Replicas"
    }
   ]
  }
 ]
}