{
 "title": "CockroachDB: Central",
 "tags": [ "CockroachDB" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster name", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Nodes: $cluster",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{cluster=\"$cluster\",pod=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Uptime: $cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sys_uptime{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mean RPC Clock Offset: $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod,cluster) (clock_offset_meannanos{cluster=\"$cluster\", pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Clock Offset: $cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (clock_offset_meannanos{cluster=\"$cluster\", pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (txn_durations:rate1m:quantile_99{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sql_exec_latency:rate1m:quantile_99{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (txn_durations:rate1m:quantile_95{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sql_exec_latency:rate1m:quantile_95{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (txn_durations:rate1m:quantile_90{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sql_exec_latency:rate1m:quantile_90{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Transaction Latency: 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (txn_durations:rate1m:quantile_50{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster SQL Latency: 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sql_exec_latency:rate1m:quantile_50{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Lease Holders Per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (replicas_leaseholders{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster Replicas Per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (replicas{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lease Holder count per Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (replicas_leaseholders{cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$cluster QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod,cluster) (sys_rss{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod,cluster) (sys_cpu_combined_percent_normalized{job='cockroachdb',cluster=\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Percentage Values",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sys_cpu_combined_percent_normalized{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage Values",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, cluster) (sys_rss{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "QPS Values",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])+rate(sql_select_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])+rate(sql_delete_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])+rate(sql_insert_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Combined"
    }
   ]
  },
  {
   "title": "QPS Values (Without Deletes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])+rate(sql_select_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval])+rate(sql_insert_count{cluster=\"$cluster\",pod=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Combined"
    }
   ]
  }
 ]
}