{
 "title": "CockroachDB: Runtime",
 "tags": [
  "CockroachDB",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=~\"$cluster\"},pod)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Node Count",
   "type": "timeseries",
   "description": "The number of live nodes in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(liveness_livenodes{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory in use across all nodes:\nRSS  \nTotal memory in use by CockroachDB\n\nGo Allocated  \nMemory allocated by the Go layer\n\nGo Total  \nTotal memory managed by the Go layer\n\nC Allocated  \nMemory allocated by the C layer\n\nC Total  \nTotal memory managed by the C layer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Total memory (RSS)"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_go_allocbytes{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "description": "The number of Goroutines across all nodes. This count should rise and fall based on load.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sys_goroutines{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Goroutine Count"
    }
   ]
  },
  {
   "title": "Runnable Goroutines per CPU",
   "type": "timeseries",
   "description": "The number of Goroutines waiting for CPU. This count should rise and fall based on load.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (sys_runnable_goroutines_per_cpu{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "description": "The number of times that Go’s garbage collector was invoked per second across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "GC Runs"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "description": "The amount of processor time used by Go’s garbage collector per second across all nodes. During garbage collection, application code execution is paused.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_gc_pause_ns{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "GC Pause Time"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "User CPU Time"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Sys CPU Time"
    }
   ]
  },
  {
   "title": "Clock Offset",
   "type": "timeseries",
   "description": "Mean clock offset of each node against the rest of the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (clock_offset_meannanos{pod=~\"$node\",cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}