{
 "title": "CockroachDB: SQL",
 "tags": [
  "CockroachDB",
  "Kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{cluster=~\"$cluster\"}"
    }
   },
   { "name": "node", "label": "Node", "query": { "query": "label_values(sys_uptime{},pod)" } },
   {
    "name": "rate_interval",
    "label": "rate_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Open SQL Sessions",
   "type": "timeseries",
   "description": "The total number of open SQL Sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (sql_conns{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open SQL Transactions",
   "type": "timeseries",
   "description": "The total number of SQL transactions currently open.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (sql_txns_open{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "The total number of transactions initiated, committed, rolled back, or aborted per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate( sql_txn_rollback_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Aborts"
    }
   ]
  },
  {
   "title": "Schema Changes",
   "type": "timeseries",
   "description": "The total number of DDL statements per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))  ",
     "legendFormat": "DDL Statements"
    }
   ]
  },
  {
   "title": "Active SQL Statements",
   "type": "timeseries",
   "description": "The total number of SQL statements currently running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sql_distsql_queries_active{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "Active Statements"
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "timeseries",
   "description": "A moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{cluster=~\"$cluster\",pod=~\"$node\"}[5m]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "SQL Statement Errors",
   "type": "timeseries",
   "description": "The number of statements which returned a planning or runtime error.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SQL Statement Contention",
   "type": "timeseries",
   "description": "The total number of SQL statements that experienced contention.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_distsql_contended_queries_count{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Contention"
    }
   ]
  },
  {
   "title": "Active Flows for Distributed SQL Statements",
   "type": "timeseries",
   "description": "The number of flows on each node contributing to currently running distributed SQL statements.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sql_distsql_flows_active{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SQL Byte Traffic",
   "type": "timeseries",
   "description": "The total amount of SQL client network traffic in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(rate(sql_bytesout{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 99th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{job=\"cockroachdb\",instance=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 90th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 90% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket{job=\"cockroachdb\",instance=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(exec_latency_bucket{job=\"cockroachdb\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(exec_latency_bucket{job=\"cockroachdb\",instance=~\"$node\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (histogram_quantile(0.90,rate(sql_txn_latency_bucket{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (histogram_quantile(0.99,rate(sql_txn_latency_bucket{job=\"cockroachdb\",cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SQL Memory",
   "type": "timeseries",
   "description": "The current amount of allocated SQL memory. This amount is what is compared against the node's --max-sql-memory flag.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (sql_mem_root_current{cluster=~\"$cluster\",pod=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Statement Denials: Cluster Settings",
   "type": "timeseries",
   "description": "The total number of statements denied per second due to a [cluster setting](https://www.cockroachlabs.com/docs/v21.1/cluster-settings.html) in the format feature.statement_type.enabled = FALSE.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (rate(sql_feature_flag_denial{cluster=~\"$cluster\",pod=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}