{
 "title": "Postgres: Central",
 "tags": [
  "Postgres",
  "Kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cnpg_collector_up{},cluster)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cnpg_collector_up{cluster=~\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Wraparound",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 22, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "repeat": "pod",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$pod</p>\n  </td>\n</table>"
   },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 2 },
   "repeat": "pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 2 },
   "repeat": "pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_streaming_replicas{cluster=\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (cnpg_backends_total{cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (cnpg_backends_total{cluster=\"$cluster\",pod=~\"$pod\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\",cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_database_xid_age{cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_postmaster_start_time{cluster=\"$cluster\",pod=~\"$pod\"}*1000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{cluster=\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{full}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 3, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 6, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Effective Cache Size",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 9, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 15, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 18, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sequential Page Cost",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 21, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
     "repeat": "pod",
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$pod</p>\n  </td>\n</table>"
     },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
     "repeat": "pod",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"max_connections\",cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"shared_buffers\",cluster=\"$cluster\",pod=~\"$pod\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"effective_cache_size\",cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"work_mem\",cluster=\"$cluster\",pod=~\"$pod\"} * 1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"maintenance_work_mem\",cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"random_page_cost\",cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"seq_page_cost\",cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Configurations",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operational Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", image!=\"\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Session States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(cnpg_backends_total{cluster=\"$cluster\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "total ({{pod}})"
      },
      {
       "expr": "sum(cnpg_backends_total{cluster=\"$cluster\",pod=~\"$pod\"}) by (state, pod)",
       "legendFormat": "{{state}} ({{pod}})"
      }
     ]
    },
    {
     "title": "Transactions [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{cluster=\"$cluster\",pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "committed ({{pod}})"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{cluster=\"$cluster\",pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "rolled back ({{pod}})"
      }
     ]
    },
    {
     "title": "Longest Transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Deadlocks [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_deadlocks{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "count ({{pod}})"
      }
     ]
    },
    {
     "title": "Blocked Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_backends_waiting_total{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage & I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tuple I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_tup_deleted{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "deleted ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_tup_inserted{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "inserted ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_tup_fetched{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "fetched ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_tup_returned{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "returned ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_tup_updated{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "updated ({{pod}})"
      }
     ]
    },
    {
     "title": "Block I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_blks_hit{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "hit ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_blks_read{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "read ({{pod}})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_pg_database_size_bytes{datname!~\"template.*\",datname!=\"postgres\",cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": " {{pod}}: {{datname}}"
      }
     ]
    },
    {
     "title": "Temp Bytes [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_database_temp_bytes{datname=\"\",cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Ahead Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL Segment Archive Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_collector_pg_wal_archive_status{value=\"ready\",cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "ready ({{pod}})"
      },
      {
       "expr": "sum by (pod) (cnpg_collector_pg_wal_archive_status{value=\"done\",cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "done ({{pod}})"
      }
     ]
    },
    {
     "title": "Archiver Status [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_archiver_archived_count{cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "archived ({{pod}})"
      },
      {
       "expr": "sum by (pod) (rate(cnpg_pg_stat_archiver_failed_count{cluster=\"$cluster\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "failed ({{pod}})"
      }
     ]
    },
    {
     "title": "Last Archive Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_pg_stat_archiver_seconds_since_last_archival{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "age ({{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_replication_lag{cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Write Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_write_lag_seconds{cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Flush Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_flush_lag_seconds{cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Replay Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_replay_lag_seconds{cluster=\"$cluster\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collector Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collection Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "cnpg_collector_collection_duration_seconds{cluster=\"$cluster\",pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_collector_last_collection_error{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "First Recoverability Point",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "cnpg_collector_first_recoverability_point{cluster=\"$cluster\",pod=~\"$pod\"}*1000 > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requested/Timed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_pg_stat_bgwriter_checkpoints_req{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "req/{{pod}}"
      },
      {
       "expr": "sum by (pod) (cnpg_pg_stat_bgwriter_checkpoints_timed{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "timed/{{pod}}"
      }
     ]
    },
    {
     "title": "Write/Sync time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pod) (cnpg_pg_stat_bgwriter_checkpoint_write_time{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "write/{{pod}}"
      },
      {
       "expr": "sum by (pod) (cnpg_pg_stat_bgwriter_checkpoint_sync_time{cluster=\"$cluster\",pod=~\"$pod\"})",
       "legendFormat": "sync/{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}